---
driver:
  name: ec2
  require_chef_omnibus: 12.14.89
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids:
    - ci-testing
  instance_type: c3.large
  interface: public
  tags:
    Env: public
    Type: test

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  log_level: debug

platforms:
  - name: ubuntu-14.04

suites:
  - name: master
    provisioner:
      client_rb:
        environment: dev1
    driver_config:
      tags:
        Name: ntp-cluster-master-ubuntu-1404
    run_list:
      - role[ntp_server]
      - recipe[ntp_cluster::default]
    attributes:
      ntp_cluster:
        monitor:
          enabled: true
          begin: echo begin
          success: echo success
          fail: echo fail
  - name: standby
    provisioner:
      client_rb:
        environment: dev2
    driver_config:
      tags:
        Name: ntp-cluster-standby-ubuntu-1404
    run_list:
      - role[ntp_server]
      - recipe[ntp_cluster::default]
    attributes:
      ntp_cluster:
        monitor:
          enabled: true
          begin: echo begin
          success: echo success
          fail: echo fail
