---
driver:
  require_chef_omnibus: 12.14.89
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[ntp_cluster::default]
    attributes:
  - name: server
    run_list:
      - role[ntp_server]
      - recipe[ntp_cluster::default]
    attributes:
      ntp_cluster:
        monitor:
          enabled: true
          begin: echo begin
          success: echo success
          fail: echo fail
