AllCops:
  Exclude:
    - .kitchen/**/*
    - test/**/*
    - vendor/**/*

# The default 79 character limit is sometimes unproductive.
LineLength:
  Max: 120

# Lining up the attributes of some methods is advantageous for readability
SpaceBeforeFirstArg:
  Enabled: false
